os: linux
arch:
 - amd64
 - ppc64le
 
language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install gfortran liblapack-dev libblas-dev automake autoconf libtool -y
script:
  - sh autogen.sh && make && make check && make distcheck
